name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ----------------------------------------
      # 1. Prepare SSH Key
      # ----------------------------------------
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      # ----------------------------------------
      # 2. Copy files to EC2
      # ----------------------------------------
      - name: Copy project files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo mkdir -p /var/www/devops-project && sudo chown -R ubuntu:ubuntu /var/www/devops-project"
          scp -o StrictHostKeyChecking=no -i private_key.pem -r * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/devops-project/


      # ----------------------------------------
      # 3. Deploy using docker-compose on EC2
      # ----------------------------------------
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd /var/www/devops-project

            # Pull latest image
            sudo docker pull rishmamn/devops-pipeline-demo:latest

            # Stop old containers if running
            sudo docker-compose down || true

            # Start new containers
            sudo docker-compose up -d
          EOF
