name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${EC2_KEY}" > private_key.pem
          chmod 600 private_key.pem

      - name: Copy project files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${EC2_USER}@${EC2_HOST} "mkdir -p /var/www/devops-project"
          scp -o StrictHostKeyChecking=no -i private_key.pem -r ./* ${EC2_USER}@${EC2_HOST}:/var/www/devops-project/

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
            cd /var/www/devops-project

            # Stop old containers
            sudo docker-compose down || true

            # Pull latest image
            sudo docker pull rishmamn/devops-pipeline-demo:latest

            # Start containers
            sudo docker-compose up -d
          EOF
